### ISSUE TITLE
SettingsTile title gets truncated

### ISSUE THREAD

**Issue by fredecodes** [juliansteenbakker/flutter_settings_ui#4] opened 2021-12-10 01:08 UTC
The title field on iOS is getting truncated to about 50% of the width of the tile, even though the subtitle is short and does not need that space.  Version 0.6.0 of settings_ui worked fine, then this bug was introduced somewhere leading up to version 1.0.0.  The issue exists on that project's GitHub page, see https://github.com/yako-dev/flutter-settings-ui/issues/78.  It was closed so I assume there was a fix that did not make it into this fork?

In this image, the top tile is good but the bottom tile has the title truncated:
<img width="348" alt="Screen Shot 2021-12-09 at 5 08 39 PM" src="https://user-images.githubusercontent.com/15000050/145500308-d3078dd2-44b5-490b-9053-4b2cd457a0ac.png">

**Comment by juliansteenbakker** [comment] 2021-12-10 07:50
The spacer that you are referring to is not present, so that can't be it.

**Comment by fredecodes** [comment] 2021-12-10 17:17
You're correct.  I verified that the bug exists on the current master branch of yaks-dev's project.  I'll dig into the code a bit more and see if I can figure out what the correct fix is.

**Comment by fredecodes** [comment] 2021-12-10 19:13
Removing the Expanded from the subtitle text fixes the issue. 

`case SettingsItemType.modal:
        if (widget.value != null) {
          rowChildren.add(
            widget.valueWidget ??
                // removed Expanded here
                Padding(
                  padding: const EdgeInsetsDirectional.only(
                    top: 1.5,
                    end: 2.25,`

 This Expanded was introduced in this submit: https://github.com/yako-dev/flutter-settings-ui/commit/f18ba8f7ae30664d7d2b13c287f42c0818e62755#diff-225cce4612c9d27c889083a827883665eaafe10b7e3ca0e158811def7e81be4f.  

I need to experiment some more to see the side effects of this change.  Hard to do because I haven't enabled null safety on my project so I can't incorporate this project code directly, meaning I have to edit it in place and clean/rebuild each time I make a change.  Anybody know a better way?

**Comment by WouterVandenputte** [comment] 2022-01-12 13:24
I'm having the same problem, but I must also add that this truncating is only present when using a regular `SettingsTile`. If a `SettingsTile.switchTile` is used, the title and subtitle are displayed without truncating.

**Comment by Butzlabben** [comment] 2022-05-26 18:28
Well, the problem is, that the `titleMaxLines` is never used in the labels in the cupertino design. I submitted a pull request with a fix for this issue:
https://github.com/juliansteenbakker/flutter_settings_ui/pull/15

**Comment by juliansteenbakker** [comment] 2022-07-21 13:19
This project will be closed since all functions are now available on the original package https://pub.dev/packages/settings_ui

**Closed by juliansteenbakker** 2022-07-21 13:19 UTC
Labels: bug
